name: CI/CD Workflow

on:
  push:
    branches:
      - test
  pull_request:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint and Build
        run: yarn build:ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start Server
        run: |
          npx serve -s ./dist &
          npx wait-on http://localhost:3000 --timeout 60000

      - name: Run E2E Tests
        run: yarn test:e2e

      - name: Run Visual Tests
        run: yarn test:visual

      - name: Reset Database
        run: yarn reset-db

      - name: Stop Server
        run: |
          kill $(lsof -t -i:3000)
